# parts stolen from crunch.io/clatter's travis config

# only run on master branch
branches:
  only:
    - master

language: bash
os: linux


before_script: # setup environment
  - sudo apt-get install pandoc
  - git clone https://${GH_TOKEN}@github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - git checkout -qf $TRAVIS_BRANCH
  - git config --global user.email "sww1235@gmail.com"
  - git config --global user.name "Stephen"

script:
  - make all
  - pwd
  - ls

deploy:
  provider: pages
  repo: sww1235.github.io
  local-dir: www
  target-branch: master
  skip-cleanup: true
  github-token: $GITHUB_API_KEY  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
