# parts stolen from crunch.io/clatter's travis config

# only run on master branch
branches:
  only:
    - master

language: bash
os: linux


before_script: # setup environment
  #- pwd
  #- ls
  - sudo apt-get install pandoc
  - git checkout -qf $TRAVIS_BRANCH
  - git config --global user.email "travis-ci@sww1235.net"
  - git config --global user.name "Robots"

script:
# now we have all files at /home/travis/build/sww1235/Personal_Website
  - make all
  #- pwd
  #- ls

after_success:
# CD out of main repo
  #- cd ..
  #- pwd
  # clone ghpages repo to website folder
  - git clone https://${GITHUB_API_KEY}@github.com/sww1235/sww1235.github.io.git website
  # move www directory contents to ghpages repo
  - cp -rf  Personal_Website/www/. website/
  # cd into ghpages repo
  - cd website
  # add files to gh pages repo and commit
  - git add -A
  # commit files to gh pages
  - git commit -m "Website as of $(date -Iseconds -u )"
  - git push


#
# deploy:
#   provider: pages
#   repo: sww1235.github.io
#   local-dir: www
#   target-branch: master
#   skip-cleanup: true
#   github-token: $GITHUB_API_KEY  # Set in the settings page of your repository, as a secure variable
#   keep-history: true
#   on:
#    branch: master
