name: Build and Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    paths:
      - 'blog-contents/**'
      - 'html-parts/**'
      - 'other-pages/**'
      - 'styles/**'
      - 'wiki/**'
      - 'Makefile'
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
     
  # build the website
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install Pandoc
        run: sudo apt-get install pandoc

      - name: build
        run: make all
        
      - name: deploy
        run: |
          git config --global user.email "gh-actions@sww1235.net"
          git config --global user.name "Robots"
          ls
          cd
          ls
          git clone https://${{secrets.GHA_DEPLOY}}@github.com/sww1235/sww1235.github.io.git website
          # move www directory contents to ghpages repo
          cp -rf  Personal_Website/www/. website/
          # cd into ghpages repo
          cd website
          # check if there were differences between existing website and newly built files.
          # allows build to succeed if the actual website pages didn't change at all.
          if ! git diff-index --quiet HEAD --; then
          # add files to gh pages repo and commit
          git add -A
          # commit files to gh pages
          git commit -m "Website as of $(date -Iseconds -u )"
          git push
          fi
            
